# Generated by Django 3.2.7 on 2021-09-18 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryID', models.SlugField(editable=False, unique=True)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
    ]
