# Generated by Django 3.2.7 on 2021-09-26 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
