# Generated by Django 3.2.7 on 2021-10-04 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='amount',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping',
            field=models.CharField(default='0', max_length=10),
        ),
    ]
