# Generated by Django 3.2.7 on 2021-09-08 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20210908_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productImgUrl',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='product_images'),
        ),
    ]
