# Generated by Django 3.2.7 on 2021-09-21 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paymentCategory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentID', models.CharField(max_length=32)),
                ('transactionID', models.CharField(blank=True, max_length=150, null=True)),
                ('amount', models.PositiveIntegerField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('mode', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='paymentCategory.paymentcategory')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
